/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class PilihMendaki extends javax.swing.JFrame {

    /**
     * Creates new form PilihMendaki
     */
    public PilihMendaki() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pilihgunung = new javax.swing.JComboBox();
        namapemandu = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        bxnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bxnoHp = new javax.swing.JTextField();
        pesan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pilihgunung.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Gunung/Bukit", "Gunung Bawang", "Bukit Kelam", "Bukit Jamur", "Bukit Macan" }));
        pilihgunung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihgunungActionPerformed(evt);
            }
        });

        namapemandu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Pemandu" }));

        jLabel1.setText("Masukkan Nama Anda");

        bxnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxnamaActionPerformed(evt);
            }
        });

        jLabel2.setText("Masukkan Nomor Handphon Yang Dapat Dihubungi");

        bxnoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxnoHpActionPerformed(evt);
            }
        });
        bxnoHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bxnoHpKeyTyped(evt);
            }
        });

        pesan.setText("Pesan");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(pilihgunung, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(namapemandu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bxnoHp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(bxnama, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namapemandu, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pilihgunung))
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bxnama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bxnoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Mendaki().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pilihgunungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihgunungActionPerformed
        // TODO add your handling code here:
        String pilihpemandu [] = {"Nama Pemandu"};
        String GnBwg [] = {"Pilih Pemandu","Aji","Ari","Yanto","Ani"};
        String bukitKelam [] = {"Pilih Pemandu", "Adi","Susanto","Amir"};
        String bukitMacan [] = {"Pilih Pemandu", "Ajumadi","Randi"};
        String bukitJamur [] = {"Pilih Pemandu","Iwan"};
        switch (pilihgunung.getSelectedIndex()) {
            case 0:
                namapemandu.removeAllItems();
                for (int i = 0; i < pilihpemandu.length; i++) {
                    namapemandu.addItem(pilihpemandu[i]);
                }
            break;
            case 1:
                namapemandu.removeAllItems();
                for (int i = 0; i < GnBwg.length; i++) {
                    namapemandu.addItem(GnBwg[i]);
                }
            break;
            case 2:
                namapemandu.removeAllItems();
                for (int i = 0; i < bukitKelam.length; i++) {
                    namapemandu.addItem(bukitKelam[i]);
                }
            break;
            case 3:
                namapemandu.removeAllItems();
                for (int i = 0; i < bukitMacan.length; i++) {
                    namapemandu.addItem(bukitMacan[i]);
                }
            break;
            case 4:
                namapemandu.removeAllItems();
                for (int i = 0; i < bukitJamur.length; i++) {
                    namapemandu.addItem(bukitJamur[i]);
                }
            break;
            default: 
        }        
    }//GEN-LAST:event_pilihgunungActionPerformed

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        // TODO add your handling code here:
        int i = bxnoHp.getText().length();
//        if (bxnama.isEditable()) {
//        javax.swing.JOptionPane.showMessageDialog(null,"Masukkan Nama Anda");
//        return;
//        } else {
//            
//        }

        if (i<11 || i>13) {
           javax.swing.JOptionPane.showMessageDialog(null,"Masukkan Nomor Dengan Benar");
        } else {
            javax.swing.JOptionPane.showMessageDialog(null,"Pemesanan Berhasil, Tunggu Admin Mengirim Pesan Kepada Anda Untuk Transaksi Dll yaaaa");
        }
    }//GEN-LAST:event_pesanActionPerformed

    private void bxnoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxnoHpActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bxnoHpActionPerformed

    private void bxnoHpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bxnoHpKeyTyped
        // TODO add your handling code here:
                char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_bxnoHpKeyTyped

    private void bxnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxnamaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bxnamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihMendaki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihMendaki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihMendaki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihMendaki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihMendaki().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bxnama;
    private javax.swing.JTextField bxnoHp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox namapemandu;
    private javax.swing.JButton pesan;
    private javax.swing.JComboBox pilihgunung;
    // End of variables declaration//GEN-END:variables
}
